### ISSUE TITLE
about set lr-image path independently because do pre-process in lr

### ISSUE THREAD

**Issue by HymEric** [LoSealL/VideoSuperResolution#28]
I want to ask if I want to set HR-image path and LR-image separately, what can I do? Because I want to de pre-processing in lr-image. Please, reply asap. Thank you very much.

**Comment by LoSealL** [comment]
You can use `custom_pairs` parser. You can refer to `SIDD` dataset in `datasets.yaml` to see how to use this.

----
Detail:
- create a new section in `datasets.yaml`, the name must be **UPPERCASE**;
- specify your training hr-image path in `train` and training lr-image path in `train_pair`. Note the path is relative to `root`.
- specify parser.
   ```yml
   MYDATA:
     train: hrdata/
     train_pair: lrdata/
     param:
       parser: custom_pairs
   ``` 

If your LR image has the same size to HR image, specify `scale=1` in model config file.
